title: coatl.dev - Software Developers
author:
  name: coatl-dev
  email: blog@coatl.dev
description: > # this means to ignore newlines until "show_excerpts:"
  We are Software Developers enabling other Software Developers. 🇲🇽

remote_theme: jekyll/minima

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  skin: classic
  date_format: "%-d %B, %Y"

  # generate social links in footer
  social_links:
    twitter: __coatldev__
    github:  coatl-dev

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
#  - about.md
#  - projects.md
plugins:
 - jekyll-feed
 - jekyll-seo-tag
